import Mathlib
import ICAH.Axioms
import ICAH.FieldOnStratum

namespace ICAH

open Cardinal Set

/-!
## M6 — A cofinal family of intermediate-size real-closed subfields

The ℕ-indexed formulation of M6 is vacuous: by König's theorem `cof 𝔠 > ℵ₀`,
so a countable family of subfields each of size `< 𝔠` can never have union of
size `𝔠`.  The honest formulation indexes the chain by the ordinal `𝔠.ord`:

> There is a **monotone** family `K : 𝔠.ord.ToType → Subfield ℝ` of
> **real-closed** subfields, each of **intermediate** size `ℵ₀ < #(K i) < 𝔠`,
> whose union is all of ℝ (hence of size `𝔠`).

Construction: fix an enumeration `e : 𝔠.ord.ToType ≃ ℝ` and a witness set
`W ⊆ ℝ` with `#W = ℵ₁` (so each level is uncountable; here `not_CH` gives
`ℵ₁ < 𝔠`, keeping every level strictly below the continuum).  Level `i` is the
relative algebraic closure of the subfield generated by `W ∪ e '' (Iio i)`.
Initial segments of `𝔠.ord` have cardinality `< 𝔠`, so each level has size
`< 𝔠`; every real `x = e j` appears at any level `i > j`, which exists because
`𝔠.ord` is a limit ordinal.
-/

/-- The index type for the cofinal family: the order type of the ordinal `𝔠.ord`
    (universe-pinned to `Type 0` so that it can be enumerated against `ℝ`). -/
abbrev ContinuumIdx : Type := continuum.{0}.ord.ToType

/-- The cofinal family witnessing the honest form of M6 (under `not_CH`). -/
theorem exists_cofinal_rc_family :
    ∃ K : ContinuumIdx → Subfield ℝ,
      Monotone K ∧
      (∀ i, IsRealClosed (K i)) ∧
      (∀ i, aleph0 < #(K i) ∧ #(K i) < continuum) ∧
      (∀ x : ℝ, ∃ i, x ∈ K i) := by
  classical
  -- Enumeration of ℝ along the ordinal 𝔠.ord.
  have hmk : #ContinuumIdx = #ℝ := by
    rw [Cardinal.mk_real]
    exact (Cardinal.mk_toType _).trans (Cardinal.card_ord _)
  obtain ⟨e⟩ := Cardinal.eq.mp hmk
  -- A fixed uncountable witness set of size ℵ₁.
  have h1ℝ : aleph 1 ≤ #ℝ := by rw [Cardinal.mk_real]; exact aleph_one_le_continuum
  obtain ⟨W, hW⟩ := Cardinal.le_mk_iff_exists_set.mp h1ℝ
  have hW_lt : #W < continuum := by
    rw [hW]; exact lt_of_le_of_ne aleph_one_le_continuum (Ne.symm not_CH)
  refine ⟨fun i => relAlgebraic (Subfield.closure (W ∪ e '' Iio i)), ?_, ?_, ?_, ?_⟩
  · -- Monotone
    intro i j hij
    exact relAlgebraic_mono (Subfield.closure_mono
      (union_subset_union_right _ (image_mono (Iio_subset_Iio hij))))
  · -- Real closed
    intro i
    exact relAlgebraic_isRealClosed _
  · -- Intermediate size
    intro i
    constructor
    · -- ℵ₀ < ℵ₁ = #W ≤ #(K i)
      have hsub : W ⊆ (relAlgebraic (Subfield.closure (W ∪ e '' Iio i)) : Set ℝ) :=
        fun x hx => le_relAlgebraic _ (Subfield.subset_closure (Or.inl hx))
      calc aleph0 < aleph 1 := aleph0_lt_aleph_one
        _ = #W := hW.symm
        _ ≤ _ := Cardinal.mk_le_mk_of_subset hsub
    · -- #(K i) < 𝔠: the generating set has size < 𝔠.
      have hIio : #(Iio i) < continuum := by
        have h1 : Ordinal.typein (α := ContinuumIdx) (· < ·) i < continuum.ord := by
          have h := Ordinal.typein_lt_type (α := ContinuumIdx) (· < ·) i
          rwa [show Ordinal.type (α := ContinuumIdx) (· < ·) = continuum.ord from
            Ordinal.type_toType _] at h
        have h2 := Cardinal.lt_ord.mp h1
        rwa [Ordinal.card_typein] at h2
      have hseg : #(e '' Iio i) < continuum :=
        lt_of_le_of_lt Cardinal.mk_image_le hIio
      have hgen : #(W ∪ e '' Iio i : Set ℝ) < continuum :=
        lt_of_le_of_lt (Cardinal.mk_union_le _ _)
          (Cardinal.add_lt_of_lt aleph0_le_continuum hW_lt hseg)
      calc #(relAlgebraic (Subfield.closure (W ∪ e '' Iio i)))
          ≤ max #(Subfield.closure (W ∪ e '' Iio i)) aleph0 := mk_relAlgebraic_le _
        _ ≤ max (max #(W ∪ e '' Iio i : Set ℝ) aleph0) aleph0 :=
            max_le_max (Subfield.cardinalMk_closure_le_max _) le_rfl
        _ < continuum :=
            max_lt (max_lt hgen aleph0_lt_continuum) aleph0_lt_continuum
  · -- Cofinal: every real appears at some level.
    intro x
    haveI : NoMaxOrder ContinuumIdx := Cardinal.noMaxOrder aleph0_le_continuum
    obtain ⟨i, hi⟩ := exists_gt (e.symm x)
    refine ⟨i, le_relAlgebraic _ (Subfield.subset_closure
      (Or.inr ⟨e.symm x, hi, e.apply_symm_apply x⟩))⟩

/-- The union of the cofinal family is all of ℝ, hence has cardinality `𝔠`,
    while every individual level has cardinality `< 𝔠`. This is the honest,
    non-vacuous content of M6. -/
theorem cofinal_family_limit_size :
    ∃ K : ContinuumIdx → Subfield ℝ,
      Monotone K ∧
      (∀ i, aleph0 < #(K i) ∧ #(K i) < continuum) ∧
      #(⋃ i, (K i : Set ℝ)) = continuum := by
  obtain ⟨K, hmono, _, hbounds, hcover⟩ := exists_cofinal_rc_family
  refine ⟨K, hmono, hbounds, ?_⟩
  have huniv : ⋃ i, (K i : Set ℝ) = Set.univ :=
    Set.iUnion_eq_univ_iff.mpr fun x => (hcover x).imp fun _ hi => hi
  rw [huniv, Cardinal.mk_univ, Cardinal.mk_real]

end ICAH
