import Mathlib
import ICAH.Axioms
import ICAH.FieldOnStratum

namespace ICAH

open Cardinal Set

/-!
## M6 — A cofinal family of intermediate-size real-closed subfields

The ℕ-indexed formulation of M6 is vacuous: by König's theorem `cof 𝔠 > ℵ₀`,
so a countable family of subfields each of size `< 𝔠` can never have union of
size `𝔠`.  The honest formulation indexes the chain by the ordinal `𝔠.ord`:

> There is a **monotone** family `K : 𝔠.ord.ToType → Subfield ℝ` of
> **real-closed** subfields, each of **intermediate** size `ℵ₀ < #(K i) < 𝔠`,
> whose union is all of ℝ (hence of size `𝔠`).

Construction: fix an enumeration `e : 𝔠.ord.ToType ≃ ℝ` and a witness set
`W ⊆ ℝ` with `#W = ℵ₁` (so each level is uncountable; here `NotCH` gives
`ℵ₁ < 𝔠`, keeping every level strictly below the continuum).  Level `i` is the
relative algebraic closure of the subfield generated by `W ∪ e '' (Iio i)`.
Initial segments of `𝔠.ord` have cardinality `< 𝔠`, so each level has size
`< 𝔠`; every real `x = e j` appears at any level `i > j`, which exists because
`𝔠.ord` is a limit ordinal.

### Optimality: `cf(𝔠)` is the exact threshold

The `𝔠.ord` index length above is not optimal.  The sharp statement is:

* **Lower bound** (`cofinal_family_length_lower_bound`, ZFC-pure): *any*
  family of subsets of ℝ, each of size `< 𝔠`, covering ℝ, has at least
  `cf(𝔠)` members — this is exactly the König/cofinality argument that made
  the ℕ-indexed formulation vacuous, now upgraded to a sharpness statement.
* **Upper bound** (`exists_cofinal_rc_family_cof_length`): a monotone family
  of intermediate-size real-closed subfields covering ℝ indexed by
  `(cf 𝔠).ord`, obtained by composing the `𝔠.ord`-indexed family with a
  fundamental sequence (`Ordinal.exists_isFundamentalSeq`).

Together: the least length of an exhausting family of intermediate strata is
exactly `cf(𝔠)`.
-/

/-- The index type for the cofinal family: the order type of the ordinal `𝔠.ord`
    (universe-pinned to `Type 0` so that it can be enumerated against `ℝ`). -/
abbrev ContinuumIdx : Type := continuum.{0}.ord.ToType

/-- The cofinal family witnessing the honest form of M6 (under `NotCH`). -/
theorem exists_cofinal_rc_family (h : NotCH) :
    ∃ K : ContinuumIdx → Subfield ℝ,
      Monotone K ∧
      (∀ i, IsRealClosed (K i)) ∧
      (∀ i, aleph0 < #(K i) ∧ #(K i) < continuum) ∧
      (∀ x : ℝ, ∃ i, x ∈ K i) := by
  classical
  -- Enumeration of ℝ along the ordinal 𝔠.ord.
  have hmk : #ContinuumIdx = #ℝ := by
    rw [Cardinal.mk_real]
    exact (Cardinal.mk_toType _).trans (Cardinal.card_ord _)
  obtain ⟨e⟩ := Cardinal.eq.mp hmk
  -- A fixed uncountable witness set of size ℵ₁.
  have h1ℝ : aleph 1 ≤ #ℝ := by rw [Cardinal.mk_real]; exact aleph_one_le_continuum
  obtain ⟨W, hW⟩ := Cardinal.le_mk_iff_exists_set.mp h1ℝ
  have hW_lt : #W < continuum := by
    rw [hW]; exact aleph_one_lt_continuum_of_notCH h
  refine ⟨fun i => relAlgebraic (Subfield.closure (W ∪ e '' Iio i)), ?_, ?_, ?_, ?_⟩
  · -- Monotone
    intro i j hij
    exact relAlgebraic_mono (Subfield.closure_mono
      (union_subset_union_right _ (image_mono (Iio_subset_Iio hij))))
  · -- Real closed
    intro i
    exact relAlgebraic_isRealClosed _
  · -- Intermediate size
    intro i
    constructor
    · -- ℵ₀ < ℵ₁ = #W ≤ #(K i)
      have hsub : W ⊆ (relAlgebraic (Subfield.closure (W ∪ e '' Iio i)) : Set ℝ) :=
        fun x hx => le_relAlgebraic _ (Subfield.subset_closure (Or.inl hx))
      calc aleph0 < aleph 1 := aleph0_lt_aleph_one
        _ = #W := hW.symm
        _ ≤ _ := Cardinal.mk_le_mk_of_subset hsub
    · -- #(K i) < 𝔠: the generating set has size < 𝔠.
      have hIio : #(Iio i) < continuum := by
        have h1 : Ordinal.typein (α := ContinuumIdx) (· < ·) i < continuum.ord := by
          have h := Ordinal.typein_lt_type (α := ContinuumIdx) (· < ·) i
          rwa [show Ordinal.type (α := ContinuumIdx) (· < ·) = continuum.ord from
            Ordinal.type_toType _] at h
        have h2 := Cardinal.lt_ord.mp h1
        rwa [Ordinal.card_typein] at h2
      have hseg : #(e '' Iio i) < continuum :=
        lt_of_le_of_lt Cardinal.mk_image_le hIio
      have hgen : #(W ∪ e '' Iio i : Set ℝ) < continuum :=
        lt_of_le_of_lt (Cardinal.mk_union_le _ _)
          (Cardinal.add_lt_of_lt aleph0_le_continuum hW_lt hseg)
      calc #(relAlgebraic (Subfield.closure (W ∪ e '' Iio i)))
          ≤ max #(Subfield.closure (W ∪ e '' Iio i)) aleph0 := mk_relAlgebraic_le _
        _ ≤ max (max #(W ∪ e '' Iio i : Set ℝ) aleph0) aleph0 :=
            max_le_max (Subfield.cardinalMk_closure_le_max _) le_rfl
        _ < continuum :=
            max_lt (max_lt hgen aleph0_lt_continuum) aleph0_lt_continuum
  · -- Cofinal: every real appears at some level.
    intro x
    haveI : NoMaxOrder ContinuumIdx := Cardinal.noMaxOrder aleph0_le_continuum
    obtain ⟨i, hi⟩ := exists_gt (e.symm x)
    refine ⟨i, le_relAlgebraic _ (Subfield.subset_closure
      (Or.inr ⟨e.symm x, hi, e.apply_symm_apply x⟩))⟩

/-- The union of the cofinal family is all of ℝ, hence has cardinality `𝔠`,
    while every individual level has cardinality `< 𝔠`. This is the honest,
    non-vacuous content of M6. -/
theorem cofinal_family_limit_size (h : NotCH) :
    ∃ K : ContinuumIdx → Subfield ℝ,
      Monotone K ∧
      (∀ i, aleph0 < #(K i) ∧ #(K i) < continuum) ∧
      #(⋃ i, (K i : Set ℝ)) = continuum := by
  obtain ⟨K, hmono, _, hbounds, hcover⟩ := exists_cofinal_rc_family h
  refine ⟨K, hmono, hbounds, ?_⟩
  have huniv : ⋃ i, (K i : Set ℝ) = Set.univ :=
    Set.iUnion_eq_univ_iff.mpr fun x => (hcover x).imp fun _ hi => hi
  rw [huniv, Cardinal.mk_univ, Cardinal.mk_real]

/-! ### Optimality: `cf(𝔠)` is the exact threshold -/

/-- **Lower bound** (ZFC-pure, no monotonicity required): any family of
    subsets of ℝ, each of size `< 𝔠`, whose union is all of ℝ, has at least
    `cf(𝔠)` members.  This is the König/cofinality obstruction upgraded from
    "the ℕ-indexed formulation is vacuous" to a sharpness statement. -/
theorem cofinal_family_length_lower_bound {ι : Type} (S : ι → Set ℝ)
    (hsize : ∀ i, #(S i) < continuum)
    (hcover : (⋃ i, S i) = Set.univ) :
    continuum.ord.cof ≤ #ι := by
  by_contra hlt
  rw [not_le] at hlt
  have hsup : (⨆ i, #(S i)) < continuum :=
    Cardinal.iSup_lt_of_lt_cof_ord hlt hsize
  have hι : #ι < continuum := hlt.trans_le (Ordinal.cof_ord_le _)
  have hunion : #(⋃ i, S i) < continuum :=
    lt_of_le_of_lt (Cardinal.mk_iUnion_le S)
      (Cardinal.mul_lt_of_lt aleph0_le_continuum hι hsup)
  rw [hcover, Cardinal.mk_univ, Cardinal.mk_real] at hunion
  exact lt_irrefl _ hunion

/-- The index type for the optimal-length family: the order type of the
    ordinal `(cf 𝔠).ord`. -/
abbrev CofContinuumIdx : Type := continuum.{0}.ord.cof.ord.ToType

/-- The optimal index length is exactly `cf(𝔠)`. -/
lemma mk_cofContinuumIdx : #CofContinuumIdx = continuum.ord.cof :=
  (Cardinal.mk_toType _).trans (Cardinal.card_ord _)

/-- **Upper bound**: a monotone family of intermediate-size real-closed
    subfields covering ℝ of length exactly `cf(𝔠)`, obtained by composing the
    `𝔠.ord`-indexed family with a fundamental sequence for `𝔠.ord`
    (`Ordinal.exists_isFundamentalSeq`: a strictly monotone cofinal map
    `Iio (cf 𝔠).ord → Iio 𝔠.ord`).

    Together with `cofinal_family_length_lower_bound`, this shows the least
    length of an exhausting family of intermediate strata is exactly
    `cf(𝔠)`. -/
theorem exists_cofinal_rc_family_cof_length (h : NotCH) :
    ∃ K : CofContinuumIdx → Subfield ℝ,
      Monotone K ∧
      (∀ i, IsRealClosed (K i)) ∧
      (∀ i, aleph0 < #(K i) ∧ #(K i) < continuum) ∧
      (∀ x : ℝ, ∃ i, x ∈ K i) := by
  obtain ⟨K, hmono, hrc, hbounds, hcov⟩ := exists_cofinal_rc_family h
  -- A fundamental sequence: strictly monotone cofinal `Iio (cf 𝔠).ord → Iio 𝔠.ord`.
  obtain ⟨f, hf⟩ := Ordinal.exists_isFundamentalSeq (o := continuum.{0}.ord) rfl
  -- Transport along the order isos `Iio o ≃o o.ToType`.
  let g : CofContinuumIdx → ContinuumIdx := fun i =>
    Ordinal.ToType.mk (f (Ordinal.ToType.mk.symm i))
  have hg_mono : Monotone g := fun i j hij =>
    Ordinal.ToType.mk.monotone
      (hf.strictMono.monotone (Ordinal.ToType.mk.symm.monotone hij))
  refine ⟨K ∘ g, hmono.comp hg_mono, fun i => hrc _, fun i => hbounds _, ?_⟩
  intro x
  obtain ⟨j, hj⟩ := hcov x
  -- Cofinality of the range of `f`: find `i` with `g i ≥ j`.
  obtain ⟨_, ⟨i, rfl⟩, hle⟩ := hf.isCofinal_range (Ordinal.ToType.mk.symm j)
  refine ⟨Ordinal.ToType.mk i, hmono ?_ hj⟩
  have h2 := Ordinal.ToType.mk.monotone hle
  rw [OrderIso.apply_symm_apply] at h2
  simpa only [g, OrderIso.symm_apply_apply] using h2

end ICAH
