import Mathlib
import ICAH.Axioms
import ICAH.SizeAwareField
import ICAH.Strata
import ICAH.Definability
import ICAH.RealClosed

namespace ICAH

open Cardinal FirstOrder FirstOrder.Language FirstOrder.Ring

/-!
## M3 — Internal field operations on strata

### Design

A `Stratum` carries a bare `Set ℝ` as its carrier. The subtype `{x : ℝ // x ∈ S}`
does **not** automatically inherit a `Field` structure unless `S` is closed under
the ring operations. We therefore introduce `SubfieldStratum` — a `Stratum` whose
carrier set is the underlying set of a `Subfield ℝ`.

For any `K : Subfield ℝ`, the subtype `K` inherits:
- `Field K` (from `Subfield.instField`)
- `LinearOrder K` (from `Subtype.instLinearOrder`)
- `IsStrictOrderedRing K` (from `Subfield.toIsStrictOrderedRing`)

These are exactly the instances required by `SizeAwareField`.

## M4 — Real-closed subfields of every intermediate cardinality

The former axioms `Real.isRealClosed`, `subfieldIsRealClosed`, and
`subfieldStratumExists` are gone:

- `Real.isRealClosed` is now a theorem (`ICAH.RealClosed`).
- `subfieldIsRealClosed` (every subfield of ℝ is real closed) was **false**
  (ℚ is a subfield of ℝ and is not real closed) and has been deleted.
- `subfieldStratumExists` is now a theorem: for every `ℵ₀ ≤ κ ≤ 𝔠` there is a
  **real-closed** subfield of ℝ of cardinality exactly `κ`
  (`exists_rc_subfield`), obtained as the relative algebraic closure
  (`relAlgebraic`) of the subfield generated by a set of size `κ`.

The only remaining model-theoretic gap is `RCFSubfieldRealElementary`, with
compatibility spelling `RCFModelComplete`: a real-closed subfield of ℝ is an
elementary substructure. This is the ℝ-specialized consequence of model
completeness of RCF / Tarski–Seidenberg needed here. Formerly a named axiom;
it is now a named `Prop` threaded through the development as an explicit
hypothesis, so this file — and the whole project — declares **zero** axioms.
-/

/-! ### Subfield → SizeAwareField -/

/-- Any subfield of ℝ with a given cardinality witness yields a `SizeAwareField`. -/
noncomputable def subfieldToSAF (K : Subfield ℝ) (κ : Cardinal) (hκ : #K = κ) :
    SizeAwareField where
  carrier  := K
  κ        := κ
  instField  := inferInstance
  instLinOrd := Subtype.instLinearOrder (fun x => x ∈ K)
  instSOrd   := Subfield.toIsStrictOrderedRing K
  hcard    := hκ

/-! ### SubfieldStratum -/

/-- A `SubfieldStratum` is a `Stratum` whose carrier set is the underlying set of
    a subfield of ℝ. This guarantees closure under `+`, `·`, `-`, `⁻¹`. -/
structure SubfieldStratum extends Stratum where
  /-- The subfield of ℝ whose underlying set is the stratum carrier. -/
  subfield : Subfield ℝ
  /-- The carrier set equals the underlying set of the subfield. -/
  h_subfield : S = ↑subfield

/-- Every `SubfieldStratum` yields a `SizeAwareField` with matching carrier and cardinal. -/
noncomputable def SubfieldStratum.toSAF (R : SubfieldStratum) : SizeAwareField :=
  subfieldToSAF R.subfield R.κ (by
    -- ↥R.subfield = {x : ℝ // x ∈ ↑R.subfield} = {x : ℝ // x ∈ R.S} by h_subfield
    have : #{x : ℝ // x ∈ (↑R.subfield : Set ℝ)} = #{x : ℝ // x ∈ R.S} :=
      Cardinal.mk_congr (Equiv.subtypeEquivRight (fun x => by rw [R.h_subfield]))
    exact this.trans R.h_card)

/-- The carrier of `R.toSAF` is definitionally `R.subfield`. -/
lemma SubfieldStratum.toSAF_carrier (R : SubfieldStratum) :
    R.toSAF.carrier = R.subfield := rfl

/-- The cardinal of `R.toSAF` equals `R.κ`. -/
lemma SubfieldStratum.toSAF_kappa (R : SubfieldStratum) : R.toSAF.κ = R.κ := rfl

/-! ### `fieldOnStratum` for SubfieldStrata -/

/-- For any `SubfieldStratum`, a `SizeAwareField` with the correct carrier and cardinal exists. -/
theorem fieldOnSubfieldStratum (R : SubfieldStratum) :
    ∃ (F : SizeAwareField), F.carrier = R.toStratum.carrier ∧ F.κ = R.κ := by
  refine ⟨R.toSAF, ?_, R.toSAF_kappa⟩
  simp only [SubfieldStratum.toSAF_carrier, Stratum.carrier]
  show (R.subfield : Type) = {x : ℝ // x ∈ R.S}
  show {x : ℝ // x ∈ (↑R.subfield : Set ℝ)} = {x : ℝ // x ∈ R.S}
  rw [R.h_subfield]

/-! ### Concrete base field: real algebraic numbers -/

/-- The real algebraic numbers `algebraicClosure ℚ ℝ` form a subfield of ℝ. -/
noncomputable def algRealSubfield : Subfield ℝ := (algebraicClosure ℚ ℝ).toSubfield

/-- The real algebraic numbers are countable: `#algRealSubfield ≤ ℵ₀`. -/
lemma algReal_card_le_aleph0 : #algRealSubfield ≤ aleph0 := by
  haveI : Algebra.IsAlgebraic ℚ (algebraicClosure ℚ ℝ) := algebraicClosure.isAlgebraic ℚ ℝ
  have h : #(algebraicClosure ℚ ℝ) ≤ max #ℚ aleph0 :=
    Algebra.IsAlgebraic.cardinalMk_le_max ℚ (algebraicClosure ℚ ℝ)
  calc #algRealSubfield
      = #(algebraicClosure ℚ ℝ) := rfl
    _ ≤ max #ℚ aleph0 := h
    _ = max aleph0 aleph0 := by rw [Cardinal.mkRat]
    _ = aleph0 := max_self _

/-- The real algebraic numbers form a `SizeAwareField` with cardinal `ℵ₀`.
    Note: `ℵ₀` does **not** satisfy `ℵ₀ < ℵ₀`, so this is a base field
    outside the ICAH stratum hierarchy. -/
noncomputable def algRealSAF : SizeAwareField :=
  subfieldToSAF algRealSubfield aleph0
    (le_antisymm algReal_card_le_aleph0 (Cardinal.aleph0_le_mk _))

/-! ### Relative algebraic closure of a subfield of ℝ -/

/-- The relative algebraic closure of `K₀ ⊆ ℝ` inside ℝ, as a subfield of ℝ. -/
noncomputable def relAlgebraic (K₀ : Subfield ℝ) : Subfield ℝ :=
  (algebraicClosure K₀ ℝ).toSubfield

lemma mem_relAlgebraic {K₀ : Subfield ℝ} {x : ℝ} :
    x ∈ relAlgebraic K₀ ↔ IsIntegral K₀ x := by
  rw [relAlgebraic, IntermediateField.mem_toSubfield, mem_algebraicClosure_iff']

/-- `K₀` is contained in its relative algebraic closure. -/
lemma le_relAlgebraic (K₀ : Subfield ℝ) : K₀ ≤ relAlgebraic K₀ := by
  intro x hx
  rw [mem_relAlgebraic]
  exact (isIntegral_algebraMap (x := (⟨x, hx⟩ : K₀)) : IsIntegral K₀ x)

/-- Relative algebraic closure is monotone in the base subfield. -/
lemma relAlgebraic_mono {K₀ K₁ : Subfield ℝ} (h : K₀ ≤ K₁) :
    relAlgebraic K₀ ≤ relAlgebraic K₁ := by
  intro x hx
  rw [mem_relAlgebraic] at hx ⊢
  obtain ⟨p, hpm, hpe⟩ := hx
  refine ⟨p.map (Subfield.inclusion h), hpm.map _, ?_⟩
  have hcomp : (algebraMap K₁ ℝ).comp (Subfield.inclusion h) = algebraMap K₀ ℝ :=
    RingHom.ext fun y => rfl
  rw [Polynomial.eval₂_map, hcomp]
  exact hpe

/-- The relative algebraic closure of any subfield of ℝ is **real closed**.

    Squares and odd-degree roots are real roots of polynomials with coefficients
    in `relAlgebraic K₀`; such roots are algebraic over `algebraicClosure K₀ ℝ`,
    hence algebraic over `K₀` by transitivity (`isIntegral_trans`), hence members. -/
theorem relAlgebraic_isRealClosed (K₀ : Subfield ℝ) :
    IsRealClosed (relAlgebraic K₀) := by
  apply isRealClosed_of_forall_root
  intro p hp hcoeff c hc
  rw [mem_relAlgebraic]
  -- Descend p to a polynomial q over the algebraic closure.
  have hlift : p ∈ Polynomial.lifts (algebraMap (algebraicClosure K₀ ℝ) ℝ) := by
    rw [Polynomial.lifts_iff_coeff_lifts]
    intro n
    exact ⟨⟨p.coeff n, (IntermediateField.mem_toSubfield _ _).mp (hcoeff n)⟩, rfl⟩
  obtain ⟨q, hq⟩ := (Polynomial.mem_lifts _).mp hlift
  have hq0 : q ≠ 0 := fun h => hp (by rw [← hq, h, Polynomial.map_zero])
  have halg : IsAlgebraic (algebraicClosure K₀ ℝ) c :=
    ⟨q, hq0, by rw [Polynomial.aeval_def, ← Polynomial.eval_map, hq]; exact hc⟩
  haveI : Algebra.IsIntegral K₀ (algebraicClosure K₀ ℝ) :=
    ⟨fun y => (Algebra.IsAlgebraic.isAlgebraic y).isIntegral⟩
  exact isIntegral_trans c halg.isIntegral

set_option synthInstance.maxHeartbeats 400000 in
/-- The relative algebraic closure does not increase infinite cardinality. -/
lemma mk_relAlgebraic_le (K₀ : Subfield ℝ) :
    #(relAlgebraic K₀) ≤ max #K₀ aleph0 := by
  -- Provide the torsion-freeness instance directly; the default search times out
  -- in the large Subfield/IntermediateField instance space.
  haveI : Module.IsTorsionFree K₀ (algebraicClosure K₀ ℝ) :=
    DivisionSemiring.to_moduleIsTorsionFree
  have h : #(algebraicClosure K₀ ℝ) ≤ max #K₀ aleph0 :=
    Algebra.IsAlgebraic.cardinalMk_le_max K₀ (algebraicClosure K₀ ℝ)
  calc #(relAlgebraic K₀)
      = #(algebraicClosure K₀ ℝ) :=
        Cardinal.mk_congr (Equiv.subtypeEquivRight fun x =>
          IntermediateField.mem_toSubfield _ x)
    _ ≤ max #K₀ aleph0 := h

/-! ### Existence of real-closed subfields of every infinite cardinality ≤ 𝔠 -/

/-- For every cardinal `ℵ₀ ≤ κ ≤ 𝔠` there is a **real-closed** subfield of ℝ of
    cardinality exactly `κ`: take the relative algebraic closure of the subfield
    generated by any set of size `κ`. -/
theorem exists_rc_subfield {κ : Cardinal} (h0 : aleph0 ≤ κ) (hc : κ ≤ continuum) :
    ∃ K : Subfield ℝ, IsRealClosed K ∧ #K = κ := by
  have hκℝ : κ ≤ #ℝ := by rw [Cardinal.mk_real]; exact hc
  obtain ⟨S, hS⟩ := Cardinal.le_mk_iff_exists_set.mp hκℝ
  refine ⟨relAlgebraic (Subfield.closure S), relAlgebraic_isRealClosed _,
    le_antisymm ?_ ?_⟩
  · calc #(relAlgebraic (Subfield.closure S))
        ≤ max #(Subfield.closure S) aleph0 := mk_relAlgebraic_le _
      _ ≤ max (max #S aleph0) aleph0 :=
          max_le_max (Subfield.cardinalMk_closure_le_max S) le_rfl
      _ = κ := by rw [hS, max_eq_left h0, max_eq_left h0]
  · have hsub : S ⊆ (relAlgebraic (Subfield.closure S) : Set ℝ) := fun x hx =>
      le_relAlgebraic _ (Subfield.subset_closure hx)
    calc κ = #S := hS.symm
      _ ≤ #(relAlgebraic (Subfield.closure S)) := Cardinal.mk_le_mk_of_subset hsub

/-- Under `NotCH`, there exists a subfield of ℝ with intermediate
    cardinality `ℵ₀ < κ < 𝔠`. Formerly a named axiom; now a theorem
    (instantiate `exists_rc_subfield` at `κ = ℵ₁`). -/
theorem subfieldStratumExists (h : NotCH) :
    ∃ (K : Subfield ℝ) (κ : Cardinal),
      aleph0 < κ ∧ κ < continuum ∧ #K = κ := by
  obtain ⟨K, _, hK⟩ := exists_rc_subfield aleph0_lt_aleph_one.le aleph_one_le_continuum
  exact ⟨K, aleph 1, aleph0_lt_aleph_one, aleph_one_lt_continuum_of_notCH h, hK⟩

/-- A `SubfieldStratum` with intermediate cardinality exists (under `NotCH`). -/
noncomputable def intermediateSubfieldStratum (h : NotCH) : SubfieldStratum :=
  let K  := (subfieldStratumExists h).choose
  let κ  := (subfieldStratumExists h).choose_spec.choose
  let hκ := (subfieldStratumExists h).choose_spec.choose_spec
  { n         := 0
    S         := ↑K
    κ         := κ
    h_card    := hκ.2.2
    h_bounds  := ⟨hκ.1, hκ.2.1⟩
    subfield  := K
    h_subfield := rfl }

/-! ### M3 — fieldOnStratum for arbitrary strata (formerly an axiom) -/

/-- Every `Stratum` admits a `SizeAwareField` with the same carrier and cardinal:
    pick a real-closed subfield `K ⊆ ℝ` with `#K = R.κ` (`exists_rc_subfield`)
    and transport its ordered-field structure across an equivalence
    `R.carrier ≃ K` (which exists by cardinality). -/
theorem fieldOnStratum (R : Stratum) :
    ∃ (F : SizeAwareField), F.carrier = R.carrier ∧ F.κ = R.κ := by
  obtain ⟨K, _, hK⟩ := exists_rc_subfield R.h_bounds.1.le R.h_bounds.2.le
  have hcard : #R.carrier = #K := by
    show #{x : ℝ // x ∈ R.S} = #K
    rw [R.h_card, hK]
  obtain ⟨e⟩ := Cardinal.eq.mp hcard
  letI instF : Field R.carrier := e.field
  letI instL : LinearOrder R.carrier := LinearOrder.lift' e e.injective
  haveI instS : IsStrictOrderedRing R.carrier :=
    Function.Injective.isStrictOrderedRing e
      (e.apply_symm_apply _) (e.apply_symm_apply _)
      (fun _ _ => e.apply_symm_apply _) (fun _ _ => e.apply_symm_apply _)
      Iff.rfl Iff.rfl
  exact ⟨{ carrier := R.carrier, κ := R.κ, instField := instF,
           instLinOrd := instL, instSOrd := instS, hcard := R.h_card },
    rfl, rfl⟩

/-! ### LOR structure instance for SubfieldStratum carriers -/

/-- Every `SubfieldStratum` carrier inherits a `LOR`-structure from its subfield.
    Registered as a global instance so that `ElementaryEmbedding` synthesis works. -/
noncomputable instance subfieldStratumLORStr (R : SubfieldStratum) :
    LOR.Structure R.toStratum.carrier :=
  have heq : R.toStratum.carrier = R.subfield := by
    show {x : ℝ // x ∈ R.S} = {x : ℝ // x ∈ (↑R.subfield : Set ℝ)}
    rw [R.h_subfield]
  heq ▸ (compatibleRingOfRing R.subfield).toStructure

/-! ### RCSubfieldStratum and the single model-theoretic hypothesis -/

/-- A `SubfieldStratum` whose subfield is real closed. By `exists_rc_subfield`,
    such strata exist at every intermediate cardinality. -/
structure RCSubfieldStratum extends SubfieldStratum where
  /-- The subfield is real closed. -/
  h_rc : IsRealClosed subfield

/-- An `RCSubfieldStratum` of cardinality `ℵ₁` (under `NotCH`). -/
noncomputable def intermediateRCSubfieldStratum (h : NotCH) : RCSubfieldStratum :=
  let hex := exists_rc_subfield aleph0_lt_aleph_one.le aleph_one_le_continuum
  { n          := 0
    S          := ↑hex.choose
    κ          := aleph 1
    h_card     := hex.choose_spec.2
    h_bounds   := ⟨aleph0_lt_aleph_one, aleph_one_lt_continuum_of_notCH h⟩
    subfield   := hex.choose
    h_subfield := rfl
    h_rc       := hex.choose_spec.1 }

/-- **The single model-theoretic hypothesis of ICAH** (besides `NotCH`):
    a real-closed subfield of ℝ is an *elementary* substructure of ℝ in the
    first-order ring language `LOR` (in which the order of a real-closed
    subfield is definable via squares).

    This is the ℝ-specialized consequence of model completeness of real-closed
    fields needed by the algebraic pillar.  It follows from
    Tarski–Seidenberg quantifier elimination, which is not yet formalized in
    Mathlib's `ModelTheory` framework — the single remaining Mathlib gap of
    this development. Note that — unlike the former axiom
    `subfieldStratumElemEmb`, which claimed this for *arbitrary* subfields and
    was false — the real-closedness hypothesis makes this a true theorem of
    model theory.

    Formerly declared as `axiom rcfModelComplete`; it is now a named `Prop`
    taken as an explicit hypothesis by the results that need it
    (Pillar B of the development). Pillar A (`ICAH.ElementaryStrata`) avoids
    it entirely via downward Löwenheim–Skolem. -/
def RCFSubfieldRealElementary : Prop :=
  ∀ R : RCSubfieldStratum,
    Nonempty (R.toSubfieldStratum.toStratum.carrier ↪ₑ[LOR] ℝ)

/-- Compatibility spelling for older statements.  This is not full model
completeness as a standalone theorem; it is the specialized real-subfield
elementarity consequence needed by Pillar B. -/
def RCFModelComplete : Prop := RCFSubfieldRealElementary

/-- Extract an elementary embedding from the `RCFModelComplete` hypothesis. -/
noncomputable def RCFModelComplete.emb (hMC : RCFModelComplete)
    (R : RCSubfieldStratum) :
    R.toSubfieldStratum.toStratum.carrier ↪ₑ[LOR] ℝ :=
  (hMC R).some

end ICAH
